version: 2.1

jobs:
  build_and_deploy_first_app:
    docker:
      - image: docker:20.10.8
    working_directory: /first-app
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.8
      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t $DOCKER_USERNAME/my-http-server .
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push $DOCKER_USERNAME/my-http-server
      - deploy_first_app:
          command: |
            # Replace this with your deployment commands
            # For example, you can use kubectl or helm to deploy the application
            echo "Deploying the first app"
            kubectl apply -f first-app.yaml
    environment:
      DOCKER_USERNAME: pk051098

  build_and_deploy_second_app:
    docker:
      - image: docker:20.10.8
    working_directory: /second-app
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.8
      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t $DOCKER_USERNAME/my-message-reverser .
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push $DOCKER_USERNAME/my-message-reverser
      - deploy_second_app:
          command: |
            # Replace this with your deployment commands
            # For example, you can use kubectl or helm to deploy the application
            echo "Deploying the second app"
            kubectl apply -f second-app.yaml
    environment:
      DOCKER_USERNAME: pk051098

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_deploy_first_app
      - build_and_deploy_second_app:
          requires:
            - build_and_deploy_first_app
